### ISSUE TITLE
@steeze-ui/vue-icon -	planned

### ISSUE THREAD

**Issue by codeyash** [steeze-ui/icons#10]
I am huge fan of your work!

This is showing planned. We have to use VueJs for our new project.

Any ideas if we can use @steeze-ui/vue-icon in our project.

**Comment by codeyash** [comment]
Any update please.

**Comment by JustinVoitel** [comment]
@codeyash  Selfishly I was hoping someone would make a draft for vue 😅 

I have never used it but I can try to hack something in the weekend. Any resources on how to init a basic vue component library for this case ?

**Comment by codeyash** [comment]
Vue 3 with Composition API is almost similar to svelte. 

https://vuejs.org/guide/extras/composition-api-faq.html

I can't find any Icon Component using Vue 3 Composition API but here are a few links.
https://github.com/qinshenxue/vue-icon/blob/master/src/vue-feather.js
https://github.com/fengyuanchen/vue-feather/blob/main/src/vue-feather.vue
[fortawesome](https://github.com/FortAwesome/vue-fontawesome/blob/2.x/src/components/FontAwesomeIcon.js)

I can help with it. I need directions.

**Comment by JustinVoitel** [comment]
@codeyash Can you please try `@steeze-ui/vue-icon@1.0.0-next.2`
Example:
```vue
<script setup>
  import {Icon} from "@steeze-ui/vue-icon"
  import {Fire} from "@steeze-ui/heroicons"
</script>

<template>
  <Icon :src=Fire theme="solid" size="24px" color="red"></Icon>
</template>
```
Tell me if anything is wrong or missing!

**Comment by codeyash** [comment]
Thanks for your wonderful work.

Working flawlessly!

If you want you can update README with a link. Right now it's not updated.

**Comment by codeyash** [comment]
Added a pull request: https://github.com/steeze-ui/icons/pull/12
