### ISSUE TITLE
css.gg Icon Set

### ISSUE THREAD

**Issue by codeyash** [steeze-ui/icons#11]
https://css.gg

It is a small yet wonderful icon set.

Is it possible to add it to the system?

**Comment by codeyash** [comment]
Added a pull request: https://github.com/steeze-ui/icons/pull/13

**Comment by JustinVoitel** [comment]
you can try the icons: `@steeze-ui/css-gg@next`

**Comment by JustinVoitel** [comment]
Thanks for your contribution :)

**Comment by codeyash** [comment]
Thanks for the merging it!

It is working great, already using it :)
