### ISSUE TITLE
Can't import Icon.svelte?

### ISSUE THREAD

**Issue by Bandit** [steeze-ui/icons#14]
```
<script>
    import { Icon } from '@steeze-ui/svelte-icon';
</script>
```

=> `Unknown file extension ".svelte" for [...]/node_modules/@steeze-ui/svelte-icon/Icon.svelte`

Also tried `import Icon from '@steeze-ui/svelte-icon/Icon.svelte'` but that doesn't work either.

Brand new install of Sveltekit with Vite 3.0.9

**Comment by JustinVoitel** [comment]
Which version of the package do you use?

**Comment by Bandit** [comment]
`1.3.1`

**Comment by JustinVoitel** [comment]
I cant really reproduce the error with a fresh kit project! 
Do you have a repo ?

**Comment by Bandit** [comment]
Lol now I can't reproduce it either after copying and pasting my above code. Extremely bizarre. Sorry about that...
