### ISSUE TITLE
Sveltekit - Vite is unable to see the modules exposed by @steeze-ui/heroicons

### ISSUE THREAD

**Issue by 0gust1** [steeze-ui/icons#16]
Made an attempt to migrate our Sveltekit project from `svelte-hero-icons`

Installed `@steeze-ui/svelte-icon` and `@steeze-ui/heroicons`, followed the instructions and got
(I tried with deps in `devDependencies` and `dependencies`)

```
Uncaught (in promise) SyntaxError: The requested module '/node_modules/.vite/deps/@steeze-ui_heroicons.js?v=4ed4dd65' does not provide an export named 'Logout' (at index.svelte? [sm]:6:12)
```

**Comment by JustinVoitel** [comment]
@0gust1 
You are probably using `@steeze-ui/heroicons@2.x` which uses Heroicons v2 under the hood with a complete rework of all icons and most of the names.

Either you update the icon names using [this link](https://github.com/tailwindlabs/heroicons/releases/tag/v2.0.0) for reference (e.g Logout -> ArrowRightOnRectangle)

Or you use `@steeze-ui/heroicons@1.1.1` using the old icons and names

I hope this helps!
