### ISSUE TITLE
icon filled

### ISSUE THREAD

**Issue by cellulosa** [steeze-ui/icons#19]
hi there, [Tabler icons](https://tabler-icons.io/) come with a filled version too. Are these available via steeze-ui/icons?

**Comment by JustinVoitel** [comment]
@cellulosa 
I have just updated the package to @tabler/icons@2.10.0 containing the new `filled` theme!

Unfortunately the following Icons don't have a `default` theme and will only display when using the `filled` theme:

ArticleFilled
BrandTikto
Circle0
Circle1
Circle2
Circle3
Circle4
Circle5
Circle6
Circle7
Circle8
Circle9
Droplet2
Hexagon0
Hexagon1
Hexagon2
Hexagon3
Hexagon4
Hexagon5
Hexagon6
Hexagon7
Hexagon8
Hexagon9
Square0
Square1
Square2
Square3
Square4
Square5
Square6
Square7
Square8
Square9
Squares
Zoom
