### ISSUE TITLE
Implement remix icons pack

### ISSUE THREAD

**Issue by pavelbelyaev98** [steeze-ui/icons#2]
Hello! a while ago I've created a package called [svelte-remix-icons](https://www.npmjs.com/package/svelte-remix-icons) , inspired by [svelte-hero-icons](https://www.npmjs.com/package/svelte-hero-icons). 

I was wondering if it is possible to implement the remix icons pack into this project so everyone can directly use this package.

**Comment by JustinVoitel** [comment]
@zommerberg sorry for the late response, but it is now implemented with the corresponding npm package `@steeze-ui/remix-icons` and a complete rewrite of the builder core (all sources now bundled in one file, better typings, smaller packages). Can you test if all is working for you ?

**Comment by pavelbelyaev98** [comment]
Works perfectly, thanks!
