### ISSUE TITLE
Request: Replace Feather Icons with Lucide Icons

### ISSUE THREAD

**Issue by t-miller** [steeze-ui/icons#20]
It appears as though Feather is dead and the community has moved to [Lucide](https://github.com/lucide-icons/lucide). Per Lucide,

> Community-run fork of [Feather Icons](https://github.com/feathericons/feather), open for anyone to contribute icons.
> 
> It began after growing disaffection with the [Feather Icons](https://github.com/feathericons/feather) project moderation. With over 300+ open issues and over 100+ open PRs, the Feather Icons project has been abandoned. This unfortunately means that hundreds of developers and designers wasted their time contributing to Feather Icons with no chance of PRs being accepted.
> 
> Lucide is trying to expand the icon set as much as possible while staying faithful to the original simplistic design language. We do this as a community of devs and designers and hope that you'll join us!
> 
> Why choose Lucide over Feather Icons
> 
> - More icons to work with: Lucide already has hundreds of icons more than Feather does.
> - Official librairies and integrations with popular frameworks and design tools.
> - Well maintained code base.
> - Active community, regularly growing and improving the set.

It would be lovely to replace the Feather icon pack in Steeze with the Lucide version.

**Comment by JustinVoitel** [comment]
@t-miller Thanks for the information! Will work on that as soon as possible.

**Comment by JustinVoitel** [comment]
@steeze-ui/lucide-icons is now available!

**Comment by t-miller** [comment]
Thank you!
