### ISSUE TITLE
Export IconSource

### ISSUE THREAD

**Issue by pasevin** [steeze-ui/icons#21]
I must say it's a great library! 
Could you export the `IconSource` type to use in our components?

**Comment by JustinVoitel** [comment]
@pasevin the IconSource type can already be exported in various ways:
```ts
// from a source package e.g heroicons:
import type { IconSource } from "@steeze-ui/heroicons/types";

// from a Icon component e.g svelte-icon
import type { IconSource } from "@steeze-ui/svelte-icon/types";
```

Please reopen if its missing for a certain package :)

**Comment by pasevin** [comment]
Oh so sorry! I missed that :)
