### ISSUE TITLE
Unknown file extension ".svelte" for /data/data/com.termux/files/home/leap-website-sveltekit/node_modules/@steeze-ui/svelte-icon/Icon.svelte

### ISSUE THREAD

**Issue by leap0x7b** [steeze-ui/icons#3]

**Comment by vhscom** [comment]
Issue descriptions are nice. Anyway, the same issue as https://github.com/JustinVoitel/svelte-hero-icons/issues/18. To get past the error add `"module": "./index.js"` to the `svelte-icon` package manifest.

**Comment by vhscom** [comment]
Issue descriptions are nice. Anyway, this is similar to https://github.com/JustinVoitel/svelte-hero-icons/issues/18. To get past the error add `"module": "./index.js"` to the `svelte-icon` package manifest.

**Comment by vhscom** [comment]
Similar to https://github.com/JustinVoitel/svelte-hero-icons/issues/18. To get past the error add `"module": "./index.js"` to the `svelte-icon` package manifest.

**Comment by JustinVoitel** [comment]
@leapofazzam123 i have added the module field in v1.2.3, can you test it ? unfortunately I can't reproduce your error. Please reopen this issue if it is still not working for you
