### ISSUE TITLE
Click Handler

### ISSUE THREAD

**Issue by JoshuaHintze** [steeze-ui/icons#34]
I'm new to Svelte but I couldn't see a way to add a click handler onto the icon.

`<Icon on:click={} />`

Didn't seem to work.

**Comment by JustinVoitel** [comment]
I dont like this idea since this means I would need to mark every Icon as a button even the ones that are only for visiblility!

You could easily create a `IconButton.svelte` wrapper component like this (including all the important a11y attributes):
```svelte
<div on:click on:keydown role="button" tabindex="0">
   <slot></slot>
</div>
``` 
Then you can use it like this:
```svelte
<IconButton on:click={()=>console.log("clicked")}>
   <Icon src={Annotation} />
</IconButton>
```

**Comment by JoshuaHintze** [comment]
Thanks Justin.
