### ISSUE TITLE
Sveltekit Issue

### ISSUE THREAD

**Issue by cycle4passion** [steeze-ui/icons#36]
I'm only after the icons, not the components. I install like....

```js
pnpm i @steeze-ui/svelte-icon

dependencies:
+ @steeze-ui/svelte-icon 1.5.0

devDependencies:
+ @steeze-ui/components 1.2.0

 WARN  Issues with peer dependencies found
.
└─┬ @steeze-ui/components 1.2.0
  └── ✕ unmet peer svelte@">= ^3.46.3": found 4.2.0
```

<img width="1101" alt="Screenshot 2023-09-20 at 7 01 45 PM" src="https://github.com/steeze-ui/icons/assets/6192217/f4870907-4a2c-4a73-9bd4-167e70ebd8bf">

Looks like they are in node_modules though.

**Comment by JustinVoitel** [comment]
@cycle4passion What svelte-kit version are you using ? 
You need to install the `@steeze-ui/heroicons` package in order to use the icons!

Also If you only want the Icons you don't need to install @steeze-ui/components as it's currently not updated/maintained.

**Comment by JustinVoitel** [comment]
@cycle4passion  reopen if its still a problem
