### ISSUE TITLE
Better handling of invalid theme names

### ISSUE THREAD

**Issue by vhscom** [steeze-ui/icons#4]
Given the following Svelte component:

```svelte
<script>
  import { Icon } from '@steeze-ui/svelte-icon';
  import { UserCircle } from '@steeze-ui/heroicons';
</script>

<Icon src={UserCircle} class="color-red" size="24" />
<Icon src={UserCircle} class="color-green" size="24" theme="solid" />
<Icon src={UserCircle} class="color-blue" size="24" theme="outline" />
```

The red and green icons are output. But blue icon is not. My expectation would be for the blue icon to output using the default theme. Alternatively, warn the user.

**Comment by JustinVoitel** [comment]
yea when implementing it I thought it would be better to show nothing when a non-existent theme was used, but thinking about it the default theme is definitely a better fallback: implemented in v1.3.0
