### ISSUE TITLE
[Request] Add Google Material Symbol Icon Set

### ISSUE THREAD

**Issue by Myphz** [steeze-ui/icons#43]
I'd do it myself, but I can't seem to understand how exactly can I add a new builder. When I install the dependencies of the monoreop with pnpm, I can't run the template builder sveltekit app - perhaps I'm missing some steps?

"Material Icons / Material Symbols

These are two different official icon sets from Google, using the same underlying designs. Material Icons is the classic set, while Material Symbols was introduced in April 2022, built on variable font technology."

Sources:
https://github.com/google/material-design-icons
https://fonts.google.com/icons

**Comment by JustinVoitel** [comment]
Icon Sets based on Fonts are currently not supported and planned for steeze-ui/icons since they work differently (steeze-ui/icons only works with svg's)
