### ISSUE TITLE
Adding internal padding changes the size of the icon

### ISSUE THREAD

**Issue by NickAnthony** [steeze-ui/icons#47]
Filing this issue because I want to call some unexpected behavior.  We're using tailwind and @steeze-ui/svelte-icon in a sveltekit app.

When adding the padding tailwind classes, the icon size changes.

So `<Icon class="w-6 h-6 pr-2" />` creates an icon with properties `<Icon class="w-4 h-4 mr-2" />`

Maybe it's WAI because we want the icon size to be constant, because technically `w-6 h-6 pr-2` would have a width of `w-8`, but I wanted to file this issue because it does not behave like other libraries we use.

**Comment by edde746** [comment]
You need to learn the difference between padding and margin. This is also not at all related to this repo.
