### ISSUE TITLE
"derived is undefined" error in v1.6 of @steeze-ui/svelte-icon when using Svelte 4

### ISSUE THREAD

**Issue by jamesscottbrown** [steeze-ui/icons#61]
The latest release (v1.6) gives an error that `derived` is undefined when used with Svelte 4. I'm not sure whether breaking backwards compatability with Svelte 4 was intended.

The new [`$derived`](https://svelte.dev/docs/svelte/$derived) syntax is used in `Icon.svelte`: https://github.com/steeze-ui/icons/blob/main/packages/components/svelte-icon/src/lib/Icon.svelte#L12
Svelte 4 interprets this as an attempt to access the value of a store called `derived` that is undefined.

(this change was introduced in https://github.com/steeze-ui/icons/pull/60)

**Comment by jamesscottbrown** [comment]
I think that compatability with both Svelte 4 and Svelte 5 could have been achieved by not using any new Svelte 5 syntax, and instead only changing package.json to specify dependency on either.

That is, change:

```
    "svelte": "^4.0.0",
```

to:
```
    "svelte": "^4 || ^5"
```

**Comment by JustinVoitel** [comment]
mistake by me, 1.6.0 should have been a major release. Svelte versions <5 must use 1.5.x
