### ISSUE TITLE
Faulty export for IconSource in @steeze-ui/heroicons

### ISSUE THREAD

**Issue by dreamscached** [steeze-ui/icons#64]
There's a problem with v2.4.1 of @steeze-ui/heroicons on NPM (which I have just tried to install as a part of svelte-hero-icons):

https://www.npmjs.com/package/@steeze-ui/heroicons?activeTab=code

![demo](https://github.com/user-attachments/assets/b190e146-3200-4339-b02f-164bb7c6cbd9)

There is no `IconSource` in that `dist.js`, which makes it impossible to use. Rolling back to v2.4.0 solved the problem as there is no such export.

**Comment by JustinVoitel** [comment]
@dreamscached I have no Idea what went wrong there in the build script but it should be fixed in v2.4.2
