### ISSUE TITLE
Adding svelte animation with transition:draw

### ISSUE THREAD

**Issue by thenbe** [steeze-ui/icons#8]
Is it possible to use svelte's [`transition:draw`](https://svelte.dev/docs#run-time-svelte-transition-draw) with the `Icon` component? If so, how would you recommend going about it? 

I tried looking through the source code, but still can't really figure out how to inject `transition:draw` into the `path` element. Thank you!

**Comment by JustinVoitel** [comment]
@ambiguous48 
I think for that case you would need to write your own Icon component like this:

https://svelte.dev/repl/843e711ee337430f852b17f2cf351e1e?version=3.46.6

(keep in mind only the icons that use a path will be drawn the way you want it e.g solid theme of heroicons wont work this way)
